# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    # Disable noisy linters for now
    - exhaustive
    - wrapcheck
    - varnamelen
    - nlreturn
    - wsl
    - gomnd
    - goerr113
    - errorlint
    - forcetypeassert
    - ireturn

linters-settings:
  errcheck:
    # Ignore these functions for errcheck
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*go.mongodb.org/mongo-driver/mongo.Client).Disconnect
      - io.Copy
      - fmt.Fprintf
      - fmt.Fprint
      - fmt.Fprintln
      - (io.Closer).Close

issues:
  # Don't limit the number of issues per linter
  max-issues-per-linter: 0
  max-same-issues: 0
